tags:
  name: Profile
  description: Endpoints para profile
components:
  schemas:
    ProfileCreate:
      type: object
      properties:
        userId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
        telephone:
          type: json
          example: {"telefono":"0999252226", "internacional":"+5164841566465"}
        country:
          type: string
          example: Ecuador
        city:
          type: string
          example: Ibarra
        economicSector:
          type: string
          example: Pesca
        linkedin:
          type: string
          example: http://linkedin/prueba
        instagram:
          type: string
          example: http://instagram/prueba
        website:
          type: string
          example: http://miwebsite
        summary:
          type: text
          example: Resumen completo del perfil del usuario
        github:
          type: string
          example: http://github/prueba
    ProfileCategoryCreate:
      type: object
      properties:
        profileId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
        categoryId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
    ProfileUpdate:
      type: object
      properties:
        telephone:
          type: json
          example: {"telefono":"0999252226", "internacional":"+5164841566465"}
        country:
          type: string
          example: Ecuador
        city:
          type: string
          example: Ibarra
        economicSector:
          type: string
          example: Pesca
        linkedin:
          type: string
          example: http://linkedin/prueba
        instagram:
          type: string
          example: http://instagram/prueba
        website:
          type: string
          example: http://miwebsite
        summary:
          type: text
          example: Resumen completo del perfil del usuario
        github:
          type: string
          example: http://github/prueba
    Profile:
      type: object
      properties:
        id:
          type: UUID
          example: ab068e82-6021-4301-b269-ffc0daf16f8e
        userId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
        telephone:
          type: json
          example: {"telefono":"0999252226", "internacional":"+5164841566465"}
        country:
          type: string
          example: Ecuador
        city:
          type: string
          example: Ibarra
        economicSector:
          type: string
          example: Pesca
        linkedin:
          type: string
          example: http://linkedin/prueba
        instagram:
          type: string
          example: http://instagram/prueba
        website:
          type: string
          example: http://miwebsite
        summary:
          type: text
          example: Resumen completo del perfil del usuario
        github:
          type: string
          example: http://github/prueba
    ProfileCategory:
      type: object
      properties:
        id:
          type: UUID
          example: ab068e82-6021-4301-b269-ffc0daf16f8e
        profileId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
        categoryId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
    ProfileUser:
      type: object
      properties:
        id:
          type: UUID
          example: ab068e82-6021-4301-b269-ffc0daf16f8e
        userId:
          type: uuid
          example: asdqw3-2sacs-12as-csa1-ascas
        telephone:
          type: json
          example: {"telefono":"0999252226", "internacional":"+5164841566465"}
        country:
          type: string
          example: Ecuador
        city:
          type: string
          example: Ibarra
        economicSector:
          type: string
          example: Pesca
        linkedin:
          type: string
          example: http://linkedin/prueba
        instagram:
          type: string
          example: http://instagram/prueba
        website:
          type: string
          example: http://miwebsite
        summary:
          type: text
          example: Resumen completo del perfil del usuario
        github:
          type: string
          example: http://github/prueba
        user:
          type: json
          example: { "id": "7d66faab-c7a8-4cd3-95b0-6e729ae3c285", "role": "pyme/users", "user": "profile2", "userType": 1, "walletAddress": "csdcds33ef23r32f43f4f4", "maturity": "medio", "avatar": "8383uefhw89weh9ew8f88fwefew8f89894fw9efh984fh","creation_time": "2021-04-26T16:03:56.000Z", "modification_time": "2021-04-26T16:03:56.000Z"}
    ProfileUpdateWithUser:
      type: object
      properties:
        avatar:
          type: string,
          example: "base 64 file"
        telephone:
          type: json
          example: {"telefono":"0999252226", "internacional":"+5164841566465"}
        country:
          type: string
          example: Ecuador
        city:
          type: string
          example: Ibarra
        economicSector:
          type: string
          example: Pesca
        linkedin:
          type: string
          example: http://linkedin/prueba
        instagram:
          type: string
          example: http://instagram/prueba
        website:
          type: string
          example: http://miwebsite
        summary:
          type: text
          example: Resumen completo del perfil del usuario
        github:
          type: string
          example: http://github/prueba